-- Idempotent copy of Spring Batch's bundled schema-sqlserver.sql (see
-- org/springframework/batch/core/schema-sqlserver.sql in spring-batch-core),
-- with every CREATE guarded by an existence check. The stock script has no
-- such guard, so with spring.batch.jdbc.initialize-schema=always (needed
-- because our SQL Server instance is persistent, not embedded) a second app
-- restart against the same database would fail with "table already exists".
-- Each guard wraps a single statement (no BEGIN/END) so Spring's script
-- runner, which splits purely on ";", still sends one full statement per
-- JDBC call.

IF OBJECT_ID('dbo.BATCH_JOB_INSTANCE', 'U') IS NULL
CREATE TABLE BATCH_JOB_INSTANCE (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT NULL,
	JOB_NAME NVARCHAR(100) NOT NULL,
	JOB_KEY NVARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

IF OBJECT_ID('dbo.BATCH_JOB_EXECUTION', 'U') IS NULL
CREATE TABLE BATCH_JOB_EXECUTION (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT NULL,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	START_TIME DATETIME DEFAULT NULL,
	END_TIME DATETIME DEFAULT NULL,
	STATUS NVARCHAR(10) NULL,
	EXIT_CODE NVARCHAR(2500) NULL,
	EXIT_MESSAGE NVARCHAR(2500) NULL,
	LAST_UPDATED DATETIME NULL,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

IF OBJECT_ID('dbo.BATCH_JOB_EXECUTION_PARAMS', 'U') IS NULL
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	PARAMETER_NAME NVARCHAR(100) NOT NULL,
	PARAMETER_TYPE NVARCHAR(100) NOT NULL,
	PARAMETER_VALUE NVARCHAR(2500),
	IDENTIFYING CHAR(1) NOT NULL,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

IF OBJECT_ID('dbo.BATCH_STEP_EXECUTION', 'U') IS NULL
CREATE TABLE BATCH_STEP_EXECUTION (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT NOT NULL,
	STEP_NAME NVARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	START_TIME DATETIME DEFAULT NULL,
	END_TIME DATETIME DEFAULT NULL,
	STATUS NVARCHAR(10) NULL,
	COMMIT_COUNT BIGINT NULL,
	READ_COUNT BIGINT NULL,
	FILTER_COUNT BIGINT NULL,
	WRITE_COUNT BIGINT NULL,
	READ_SKIP_COUNT BIGINT NULL,
	WRITE_SKIP_COUNT BIGINT NULL,
	PROCESS_SKIP_COUNT BIGINT NULL,
	ROLLBACK_COUNT BIGINT NULL,
	EXIT_CODE NVARCHAR(2500) NULL,
	EXIT_MESSAGE NVARCHAR(2500) NULL,
	LAST_UPDATED DATETIME NULL,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

IF OBJECT_ID('dbo.BATCH_STEP_EXECUTION_CONTEXT', 'U') IS NULL
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT NVARCHAR(MAX) NULL,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

IF OBJECT_ID('dbo.BATCH_JOB_EXECUTION_CONTEXT', 'U') IS NULL
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT NVARCHAR(MAX) NULL,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'BATCH_STEP_EXECUTION_SEQ')
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CACHE NO CYCLE;

IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'BATCH_JOB_EXECUTION_SEQ')
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CACHE NO CYCLE;

IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'BATCH_JOB_INSTANCE_SEQ')
CREATE SEQUENCE BATCH_JOB_INSTANCE_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CACHE NO CYCLE;
